kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: linuxdirection #the name space you will assign role to
  name: devops-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
