apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-auth-dex
  namespace: kube-system
spec:
  secretName: cert-auth-dex
  dnsNames:
    - dex.k8s.akadeemia.cloud
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dex.k8s.akadeemia.cloud
  issuerRef:
    name: le-clusterissuer
    kind: ClusterIssuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-auth-login
  namespace: kube-system
spec:
  secretName: cert-auth-login
  dnsNames:
    - login.k8s.akadeemia.cloud
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - login.k8s.akadeemia.cloud
  issuerRef:
    name: le-clusterissuer
    kind: ClusterIssuer
