global:
  deployEnv: prod

tls:
  certificate: |-
    -----BEGIN CERTIFICATE-----
    _replace_me with certificate
    you copied from master node
    -----END CERTIFICATE-----
  key: |-
    -----BEGIN RSA PRIVATE KEY-----
    _replace_me with private key
    you copied from master node
    -----END RSA PRIVATE KEY-----

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx #if you use another ingress , replace nginx with it
    kubernetes.io/tls-acme: "true"  #cert-manager annotaion
  path: /
  hosts:
    - dex.k8s.akadeemia.cloud #_replace_me with your dex url
  tls:
    - secretName: cert-auth-dex
      hosts:
        - dex.k8s.akadeemia.cloud #_replace_me with your dex url

serviceAccount:
  create: true
  name: dex-auth-sa

config: |
  issuer: https://dex.k8s.akadeemia.cloud/ #_replace_me with your dex url
  storage: 
    type: sqlite3
    config:
      file: /var/dex.db
  web:
    http: 0.0.0.0:5556
  frontend:
    theme: "coreos"
    issuer: "Example Co"
    issuerUrl: "https://akadeemia.cloud" #_replace_me with your domain
    logoUrl: https://akadeemia.cloud/images/logo-250x25.png #_replace_me with your logo url
  expiry:
    signingKeys: "6h"
    idTokens: "24h"
  logger:
    level: debug
    format: json
  oauth2:
    responseTypes: ["code", "token", "id_token"]
    skipApprovalScreen: true
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: https://dex.k8s.akadeemia.cloud/callback #_replace_me with your dex url
      orgs:
      - name: linuxdirection
        teams:
        - devops

  staticClients:
  - id: dex-k8s-authenticator
    name: dex-k8s-authenticator
    secret: #_replace_me_with_random_secret
    redirectURIs:
      - https://login.k8s.akadeemia.cloud/callback/ #_replace_me with your dex url

envSecrets:
  GITHUB_CLIENT_ID: "09" #_replace_me 
  GITHUB_CLIENT_SECRET: "5728" #_replace_me
